name: learn-github-actions
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Install node modules
        run: npm ci
      - run: npm run build