name: learn-github-actions
on: [push]
jobs:
  build_and_deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Install node modules
        run: | 
          npm ci
          cd infrastructure
          npm ci
          cd ..
      - run: npm run build
      - run: npm run deploy